### ISSUE TITLE
Problem with empty relion classes

### ISSUE THREAD

**Issue by azazellochg** [cianfrocco-lab/Automatic-cryoEM-preprocessing#10]
Stdev for these classes is 0, so the following code will fail: https://github.com/cianfrocco-lab/Automatic-cryoEM-preprocessing/blob/df9ffe795b020c5ed1c2830ac8776de02edc6fba/cryoassess/classavg_preprocessing_p.py#L30

Suggested fix: img = (img - mean) / (std+0.00001)

**Comment by yilaili** [comment]
The classavg2jpg_p.py (line 75) first checks whether the class average is empty by checking if the sum of all pixels is zero and only converts the non-empty ones. But thanks for pointing it out and I will update it in the next release (soon)!
