### ISSUE TITLE
git clone command is missing in the installation instructions. 

### ISSUE THREAD

**Issue by alburse** [cianfrocco-lab/Automatic-cryoEM-preprocessing#19]
I would suggest adding the git clone command into installation instructions.

#navigate to the local path for the installation files to be downloaded with git clone
cd /path/to/local/clone

#clone the installation files
git clone https://github.com/cianfrocco-lab/Automatic-cryoEM-preprocessing.git

#install
pip install path/to/local/clone/Automatic-cryoEM-preprocessing/

Alpay

**Comment by yilaili** [comment]
Thanks for the suggestion! We have updated the readme file.
