### ISSUE TITLE
2dassess run issue

### ISSUE THREAD

**Issue by mplockhartuom** [cianfrocco-lab/Automatic-cryoEM-preprocessing#8]
I really like the whole concept and have been trying to go through some more challenginmg data with the micros select and 2D class selection.

# Issue
Something I have had trouble with is the GPU pip install version where:

```
2dassess -i Class2D/job007/run_it025_classes.mrcs -m useful_scripts/micassess_051419.h5
  File "/home/cryo-programs/anaconda3/envs/cryoassess/bin/2dassess", line 5
    from cryoassess.2dassess import main
                    ^
SyntaxError: invalid syntax
```

## Installation
When installing through pip i Installed it as shown on the main page and the micassess works but class does not. However 2dasses does work if I just run `python 2dassess.py`. Could the `cryoassess.2dassess` need renaming, or could have I installed this wrong?

##OS
I'm using Ubuntu 18 LTS.

thank you in advance
Mike

**Comment by MishaKopylov** [comment]
Friendly bump - same issue here.
Please advise.
--
Misha

**Comment by yilaili** [comment]
Sorry for getting back to this so late - I think this issue was fixed. Sorry about that!
