### ISSUE TITLE
Falcon

### ISSUE THREAD

**Issue by dhaselb** [cianfrocco-lab/Automatic-cryoEM-preprocessing#9]
Is there support for the Falcon?

**Comment by yilaili** [comment]
We didn't have any Falcon images in the training dataset, but I would love to see the performance on Falcon micrographs if you want to try! Also if you want to share your Falcon images with us we can try to either retrain the current model or train a new model with Falcon images as well.

**Comment by dhaselb** [comment]
Thank you for the swift reply.  I will give it a try. I was just wondering as it was not mentioned. I am also happy to share a datasets. But they are large. Do you have a possibility to load them up somewhere? 

Best, 

David

**Comment by dhaselb** [comment]
I tried with Falcon data and didn't perform too badly. It was just slightly harsh and put many good micrographs in bad.

**Comment by yilaili** [comment]
You can lower the determination threshold to include more good micrographs. For sharing datasets, we use Globus for large file transfer. Are you familiar with that? If so I can share an endpoint with you so that you can transfer the data to us. Thanks a lot!!
